### ISSUE TITLE
roslices, romaps: add iteration method 

### ISSUE THREAD

**Issue by phelmkamp** [phelmkamp/immut#3]
Add a method for iteration of elements, e.g.

```go
func (s Slice[E]) Do(fn func(E)) {}
```

Alternative names:
- Range
- ForEach

**Comment by phelmkamp** [comment]
Added new method `romaps.Map.Do`. Benchmarks show this is faster than iterating over the result of `romaps.Keys`.

Decided against adding `roslices.Slice.Do` after benchmarks showed it's slower than a `for` loop over `roslices.Slice.Index`, e.g.
```go
for i := 0; i < s.Len(); i++ {
	v := s.Index(i)
}
```

**Comment by nioushajafari** [comment]
Thanks for this, but sometimes readability of the code is more important than the performance. Plenty of projects could be very happy with a roslices.Slice.Do instead of a for loop. 

Thanks anyway.
